### ISSUE TITLE
Provide a rake task to re-schedule all scheduled jobs

### ISSUE THREAD

**Issue by alikhajeh1** [rightscale/scheduled_job#20] opened 2015-01-30 10:43 UTC
We currently use this gem in a few repos, and in every one of those repos, we've added our own rake task that's used to "kick-off" the jobs by calling `.schedule_job` on them. It might be possible do to look for all classes that include ScheduledJob and make this rake task part of the gem.
```
namespace :jobs do
  task :reschedule => :environment do
    all_jobs.each { |job| job.schedule_job }
  end
```

**Comment by CallumD** [comment] 2015-01-31 20:47
I have something working for this. There a couple of issues that came up which I have had to work around.

Sometimes we include scheduled job in a parent class then inherit in the child classes. I was able to work around this by scheduling classes that have the module included and respond to time_to_recur or are descendants of that job. This would be fine however we need to ensure then that each of the children define there own time_to_recur. Not sure if its just better forcing them to include the module.

Secondly we will have no control over which jobs are not included when the reschedule is performed. Essentially anything that included scheduled_job will get scheduled where as at the moment we use the all jobs array to control which gets scheduled. Again we could add some method or constant to control this. I will put in a PR for where I have got to and reference this issue.

**Comment by alikhajeh1** [comment] 2015-02-03 18:07
> This would be fine however we need to ensure then that each of the children define there own time_to_recur.

Why would each child job have to define its own time_to_recur? Won't they just inherit the parent's method and respond to time_to_recur anyway? Maybe I'm missing something...

> Again we could add some method or constant to control this.

There might be some rare cases where a user defines a ScheduledJob but doesn't want them to be auto-scheduled by this rake task. Given that this is probably not the norm, maybe we can add a SKIP_WHEN_SCHEDULING_VIA_RAKE=true or some thing along those lines so we skip that job in the rake task? Maybe @smcgivern or @aliscott have a better idea on how to handle this?

**Comment by smcgivern** [comment] 2015-02-03 18:17
AIUI, the problem is that we have classes which include `ScheduledJob` which are only meant to be used as base classes, not directly?

Another solution (haven't thought this through): get SJ to provide a `schedulable?` method that defaults to `true`. Then parent classes can override this to `false`, forcing any subclasses which want to be scheduled to define it themselves. I don't see a problem with inheriting `time_to_recur`, that seems useful to be.

In our particular case, it seems we could also solve this by making the base class a module rather than a class, and just having the child classes include it. I can't link here, obviously, and that's really a separate point, I just wanted to bring it up.

**Comment by smcgivern** [comment] 2015-02-03 18:18
For some reason I read @alikhajeh1's suggestion of a constant as an env var; I basically just suggested the same thing :smiley:

**Comment by aliscott** [comment] 2015-02-03 18:35
+1 on `schedulable?`

**Comment by CallumD** [comment] 2015-02-03 18:37
ok I'm not keen on putting in constants or boolean methods to denote that the job is not a parent class as it just feels like clutter. 

A simple solution is to force the use to put the include on the child class that way time to recur can be shared and the implementer is making a conscious choice to put the include on the classes that are to be scheduled. 

That way we can have schedulable? implemented in SJ as @smcgivern suggests and the implementer can have that return false if they dont wan the job to automatically get picked up in the reschedule.

**Comment by alikhajeh1** [comment] 2015-02-09 15:17
Given there's also https://github.com/rightscale/scheduled_job/issues/22, maybe we should introduce a config hash that lets users define which jobs should be auto-rescheduled and how many of each they want scheduled?

**Comment by CallumD** [comment] 2015-02-16 09:25
closed by https://github.com/rightscale/scheduled_job/pull/21

**Closed** 2015-02-16 09:25 UTC
Labels: enhancement
